# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Honoka Suzuki
# title: Senior Network System Administrator
email: honokasuzuki@outlook.com
website: https://honokasuzuki.github.io/

# Social links
github_username:  honokasuzuki
linkedin_username: honoka-suzuki

# About Section
# about_title: About Me
about_profile_image: images/headshot_small.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Honoka.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
