# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Honoka Suzuki
title: PhD Student
email: hsuzuki AT unc DOT edu
website: https://honokasuzuki.github.io/academic

# Social links
github_username:  honokasuzuki
linkedin_username: honoka-suzuki

# About Section
# about_title: About Me
# about_profile_image: images/headshot_small.JPG
about_content: | # this will include new lines to allow paragraphs
  Hi, thanks for visiting! 
  
  I am a Ph.D. student in Quantitative Psychology at the University of North Carolina at Chapel Hill. Prior to starting my Ph.D. program, I worked as a data scientist at an 
  international education company and obtained my B.S. in Applied Math and Statistics from the University of Notre Dame. My interests revolve around machine learning,  
  psychometrics, and anything that involves quantitative analysis of social science data.
  
  In my free time, I enjoy (healthy) baking, going on picnics, and making fashion illustrations.


# Projects Section
projects_title: GitHub Pages

# Experience Section
experience_title: Relevant Experience

# Education Section
educaton_title: Education

# MMore Section
#more_title: Publications and Presentations
#more_content: | # this will include new lines to allow paragraphs
#  - Suzuki, H., Hong, M., Ober, T., & Cheng, Y. (2020). Applying Machine Learning to Predict Differences between Learning Outcomes. Under Review.
  
#  - Ober, T. M., Coggins, M. R., Rebouças-Ju, D., Suzuki, H., & Cheng, Y. (in press). Effect of teacher support on students’ math attitudes: Measurement and moderation of students’ background characteristics. Contemporary Educational Psychology.

#  - Suzuki, H., Hong, M., Ober, T., & Cheng, Y. (2020, Mar 20–22). Machine Learning on Student Learning: Modeling Differences Between Various Student Learning Outcomes in AP Statistics Classrooms [Poster Session 1]. ACC Meeting of the Minds Conference at the University of North Carolina, Chapel Hill, NC, United States. https://accmom2020.web.unc.edu/ (Conference canceled due to COVID-19)

#  - Galvao, D. & Suzuki, H. (2019, Nov 1). Using Real-Time Occupancy Data to Understand and Influence Student Behavior [Poster Session 2]. Undergraduate Research and Experiential Learning Showcase at the University of Notre Dame, Notre Dame, IN, United States. https://cuse.nd.edu/undergraduate-research/sharing-research/presenting-research/undergraduate-research-and-experiential-learning-showcase/

   
# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
